add_newline = true

[hostname]
ssh_symbol = 'ğŸŒ'

[nodejs]
disabled = true

[package]
disabled = true

[python]
format = 'via [${symbol}${pyenv_prefix}($virtualenv )]($style)'

[rust]
disabled = true

format = "$all"
